[project]
name = "project-2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "requests>=2.32.5",
]

[dependency-groups]
production = [
    "gunicorn>=23.0.0",
]
staging = [
    "jinja2>=3.1.6",
]
